### ISSUE TITLE
Home assistant, unable to use this to speak

### ISSUE THREAD

**Issue by cooljimy84** [Geeked-Out-Solutions/mycroftapi#5]
I've got a forum post open, as i can't see to get Home Assistant to push speech to my mycroft mk1 unit. I can't see any errors HASS side or Mycroft side.

Do i need to add a JSON item in to mycroft.conf so i can use this API HASS side ?

[https://community.home-assistant.io/t/mycroft-notifcations/26780/3](url)

**Comment by btotharye** [comment]
You probably have the mark 1 firewall on, try doing ufw allow 8181 from the ssh session on mark 1 and see if that resolves it.

**Comment by cooljimy84** [comment]
Fixed, many thanks for this.
/facepalm\
